.Dt SQLITE3_VTAB_COLLATION 3
.Os
.Sh NAME
.Nm sqlite3_vtab_collation
.Nd Determine The Collation For a Virtual Table Constraint
.Sh SYNOPSIS
.In sqlite.h
.Ft const char *
.Fo sqlite3_vtab_collation
.Fa "sqlite3_index_info*"
.Fa "int"
.Fc
.Sh DESCRIPTION
This function may only be called from within a call to the xBestIndex
method of a virtual table.
.Pp
The first argument must be the sqlite3_index_info object that is the
first parameter to the xBestIndex() method.
The second argument must be an index into the aConstraint[] array belonging
to the sqlite3_index_info structure passed to xBestIndex.
This function returns a pointer to a buffer containing the name of
the collation sequence for the corresponding constraint.
.Sh IMPLEMENTATION NOTES
These declarations were extracted from the
interface documentation at line 8829.
.Bd -literal
SQLITE_API SQLITE_EXPERIMENTAL const char *sqlite3_vtab_collation(sqlite3_index_info*,int);
.Ed
